app:
  name: "name_web"
  mode: "dev"
  port: 8961
  version: "v0.1.3"
  start_time: "2021-07-01"
  machine_id: 1
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 20
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 13316
  user: "root"
  password: "root"
  db_name: "reddit"
  max_open_conns: 100
  max_idle_conns: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  poll_size: 100

  
